name: spam_delection_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3

  # Google Sign-In for Firebase Authentication
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  http: ^1.2.2
  flutter_spinkit: ^5.1.0
  date_picker_plus: ^3.0.2
  flutter_bloc: ^8.1.6

  intl_phone_field: any
  curved_navigation_bar: any
  equatable: any
  shared_preferences: ^2.3.3
  fast_contacts: ^4.0.0
  permission_handler: ^11.3.1
  pricing_cards: ^0.0.8
  image_picker: ^0.8.8+7
  path_provider: ^2.0.11
  modal_progress_hud_nsn: ^0.5.1
  # call_log: ^4.0.0
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  cached_network_image: ^3.4.1
  call_e_log: ^0.0.4
  # flutter_localization: ^0.2.2

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  direct_call_plus: ^1.0.4
  url_launcher: ^6.3.1
  phone_state: ^2.0.1
  system_alert_window: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_phone_number_input: ^0.7.0+2
  country_picker: ^2.0.19
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Robooto
      fonts:
        - asset: assets\fonts\Roboto-Black.ttf
        - asset: assets\fonts\Roboto-BlackItalic.ttf
        - asset: assets\fonts\Roboto-Bold.ttf
        - asset: assets\fonts\Roboto-Italic.ttf
        - asset: assets\fonts\Roboto-Light.ttf
          weight: 700

flutter_intl:
  enabled: true
