-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg15UNoz0LALxRspQJ
LeELAvnYkWZbqpzLwbuu95Eb6jugCgYIKoZIzj0DAQehRANCAASPcXHxaFAOFQsS
qhJqdnQEIJiniQEwhSLYRp6brHDG9sGSUIWoBZjbmTtz435R/86Iw+RWNe14wr4r
0QfgKe7K
-----END PRIVATE KEY-----