// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmjejPvZIPjPdHeFBYGf8BtfEPpTSRAaE',
    appId: '1:1036303425157:web:1f85a9eb7fab7b2c8713ec',
    messagingSenderId: '1036303425157',
    projectId: 'spam-detect-cfb50',
    authDomain: 'spam-detect-cfb50.firebaseapp.com',
    storageBucket: 'spam-detect-cfb50.firebasestorage.app',
    measurementId: 'G-5EJQNTQZNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChS9sWQVNwB0_KnbwRfGvfKo11asiTyso',
    appId: '1:1036303425157:android:7bc901196f1729c98713ec',
    messagingSenderId: '1036303425157',
    projectId: 'spam-detect-cfb50',
    storageBucket: 'spam-detect-cfb50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyn60nH-lcCOXetx_xfnAXjv9Lz1plv-k',
    appId: '1:1036303425157:ios:2eefef07a598c87a8713ec',
    messagingSenderId: '1036303425157',
    projectId: 'spam-detect-cfb50',
    storageBucket: 'spam-detect-cfb50.firebasestorage.app',
    androidClientId: '1036303425157-0q2f94vuqs8kvldvthlgssfovk7ec7l5.apps.googleusercontent.com',
    iosClientId: '1036303425157-j4n2boiv56e4jr5dppojk5jg3acs21ao.apps.googleusercontent.com',
    iosBundleId: 'com.broadlink.protect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyn60nH-lcCOXetx_xfnAXjv9Lz1plv-k',
    appId: '1:1036303425157:ios:6819cd9176cd2c278713ec',
    messagingSenderId: '1036303425157',
    projectId: 'spam-detect-cfb50',
    storageBucket: 'spam-detect-cfb50.firebasestorage.app',
    androidClientId: '1036303425157-0q2f94vuqs8kvldvthlgssfovk7ec7l5.apps.googleusercontent.com',
    iosClientId: '1036303425157-ua0gfbcrr286aehm05559bk9ueta15s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.spamDelectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmjejPvZIPjPdHeFBYGf8BtfEPpTSRAaE',
    appId: '1:1036303425157:web:45712c99fddf80478713ec',
    messagingSenderId: '1036303425157',
    projectId: 'spam-detect-cfb50',
    authDomain: 'spam-detect-cfb50.firebaseapp.com',
    storageBucket: 'spam-detect-cfb50.firebasestorage.app',
    measurementId: 'G-DGXY9E370M',
  );
}
